name: Spring Web Captor CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: spring-web-captor-jars
          path: |
            spring-web-captor/target/*.jar
            spring-web-captor-xml/target/*.jar